### ISSUE TITLE
$0 & 0

### ISSUE THREAD

**Issue by modulovalue** [simolus3/tar#15]
https://github.com/simolus3/tar/blob/32f020343b9ae2d71e29008d58efd14634422f39/lib/src/constants.dart#L85-L88

is the second case here correct or a typo?

**Comment by modulovalue** [comment]
Some tests fail if that case is removed. False alarm!

**Comment by simolus3** [comment]
Yeah, `\0` is used by some old tar implementations which may either resolve to `TypeFlag.reg` or `TypeFlag.dir` which is transparently handled by the reader.
