### ISSUE TITLE
Add example for multiple files?

### ISSUE THREAD

**Issue by UNIcodeX** [simolus3/tar#16]
It might be beneficial to add an example for writing multiple files to the tar archive.

```dart
import 'dart:convert';
import 'dart:io';
import 'package:tar/tar.dart';

Future<void> main() async {
  final output = File('test.tar').openWrite();
  StreamController<TarEntry> _streamController = StreamController<TarEntry>();

  Stream<TarEntry> _entries = _streamController.stream;

  _streamController.add(
    TarEntry.data(
      TarHeader(
        name: 'file_1.txt',
        mode: int.parse('644', radix: 8),
      ),
      utf8.encode('First file.'),
    ),
  );

  _streamController.add(
    TarEntry.data(
      TarHeader(
        name: 'file_2.txt',
        mode: int.parse('644', radix: 8),
      ),
      utf8.encode('Second file.'),
    ),
  );

  await _entries.pipe(tarWritingSink(output));
}
```

**Comment by simolus3** [comment]
I think the example should point out that _any_ stream of entries can be converted to a tar stream, at the moment its not really doing a good job at that :D

`Stream.value` was just the simplest example, but even in your case I'd still prefer using `Stream.fromIterable` with a list. I'll add another example using `async*` generators to archive a directory.

**Comment by simolus3** [comment]
I've added a more complex example in dc44e03347d60e3641ae596cdcc2ed7b0e321565, I hope that helps! I've also rewritten the readme a bit to make it clearer that any stream of tar entries works.
