### ISSUE TITLE
tar extraction generates corrupt data

### ISSUE THREAD

**Issue by anaisbetts** [simolus3/tar#20]
When trying to run the code discussed in #18, certain (many?) files end up being corrupted and replaced with what appears to be the buffer serialized as numbers:

![image](https://user-images.githubusercontent.com/1396/154543709-2f4eeb73-cade-44bd-b3ef-d90cb3f737ed.png)

**Comment by simolus3** [comment]
Oh wow, that's bizarre... I tried to reproduce this with a bunch small tar files where I use the same snippet and call `toUpperCase()` on the file name. That doesn't appear to affect contents though.

Do you have small tar file where you've seen this behavior so I can reproduce it? I assume it happens with the arch bootstrap tar, but I'm wondering if you have a smaller repro or any files in particular for me to look at?

**Comment by anaisbetts** [comment]
@simolus3 I do not, sorry :(   Here's the current code I'm using if it helps:

```dart
Future<void> convertArchBootstrapToWSLRootFs(
  String archImage,
  String targetRootfsFile,
) async {
  final inputStream = File(archImage).openRead().transform(gzip.decoder);
  final writer = tarWritingSink(File(targetRootfsFile).openWrite());
  final initialFolder = RegExp(r'^root\.(x86_64|aarch64)\/');
  final ignorePkgList = RegExp(r'^root.*\/pkglist.*\.txt$');

  await TarReader.forEach(inputStream, (entry) async {
    // NB: There is a useless file inside the root.ARCH folder, we'll ignore it
    if (ignorePkgList.hasMatch(entry.name)) {
      return;
    }

    final h = entry.header;
    final header = TarHeader(
      name: h.name.replaceFirst(initialFolder, './'),
      format: h.format,
      typeFlag: h.typeFlag,
      modified: h.modified,
      linkName: h.linkName?.replaceFirst(initialFolder, './'),
      mode: h.mode,
      size: h.size,
      userId: h.userId,
      groupId: h.groupId,
      accessed: h.accessed,
      changed: h.changed,
      devMajor: h.devMajor,
      devMinor: h.devMinor,
    );

    await writer.addStream(Stream.value(TarEntry(header, entry.contents)));
  });

  await writer.close();
}
```

**Comment by simolus3** [comment]
Ok, so after a bit of digging I found out that the weird numbers are part of the original tar file (they belong to `root.x86_64/usr/share/tc/*.dist`). Now the question is why a chunk ends up in the wrong file in the end. This error doesn't happen when I buffer the contents of individual entries before writing them, so I assume there's another race condition somewhere in this package.

**Comment by simolus3** [comment]
It looks like the problem is gone with 012050e3fc92ef5068b7415f15751e0083263dee. I don't fully understand why, perhaps there's something weird going on in the file sink implementation from `dart:io` (it certainly shouldn't re-order chunks).

I'll wait for your PR and then release a new version :)
