### ISSUE TITLE
Read a tar.gz

### ISSUE THREAD

**Issue by bsutton** [simolus3/tar#21]
Does this library support reading tar.gz files?

If so, can we please get some documentation on how to do it.

**Comment by simolus3** [comment]
Yes, and this is mentioned in [the readme](https://github.com/simolus3/tar#reading):

> To read `.tar.gz` files, transform the stream with `gzip.decoder` before passing it to the `TarReader`.

So you would use something like `TarReader(file.openRead().transform(gzip.decoder))`

**Comment by bsutton** [comment]
So iI tried that and it fails.

This code works if I ungzip the file first and remove the call to .transform.

The error occurs on the second iteration when it calls to moveNext()

Here is my code:
```dart
Future<void> extractTar(
    String pathToTarGz, String pathToExtractionPoint) async {
   final reader =
      TarReader(File(pathToTarGz).openRead().transform(gzip.decoder));

  while (await reader.moveNext()) {
    final entry = reader.current;
    final path = join(pathToExtractionPoint, entry.name);
    switch (entry.type) {
      case TypeFlag.dir:
        if (!exists(path)) {
          await core.createDir(path, recursive: true);
        }
        break;

      case TypeFlag.reg:
      case TypeFlag.regA:
        // // write each entry from the tar to disk under the [tmp] folder
        if (!exists(dirname(path))) {
          await core.createDir(dirname(path), recursive: true);
        }
        final a = File(path);
        await entry.contents.pipe(a.openWrite());
        break;
      case TypeFlag.link:
      case TypeFlag.symlink:
        symlink(path, join(pathToExtractionPoint, entry.header.linkName));
        break;
      // ignore: no_default_cases
      default:
        throw UnexpectEntryTypeInTar('$pathToTarGz $path Type: ${entry.type}');
    }
  }
  // }, create: false, suffix: 'tar.gz', keep: true);
}
```

And the error is :
``` 
Unhandled exception:
'package:tar[/src/utils.dart]()': Failed assertion: line 515 pos 16: 'state == _StreamState.initial || state == _StreamState.attached': is not true.
package:tar/src/utils.dart:515
#0      _AssertionError._doThrowNew (dart:core-patch[/errors_patch.dart:51:61]())
#1      _AssertionError._throwNew (dart:core-patch[/errors_patch.dart:40:5]())
#2      BlockReader.nextBlocks.<anonymous closure>
package:tar/src/utils.dart:515
#3      _runGuarded (dart:async[/stream_controller.dart:814:24]())
#4      _StreamController._recordPause (dart:async[/stream_controller.dart:759:5]())
#5      _ControllerSubscription._onPause (dart:async[/stream_controller.dart:854:17]())
#6      _BufferingStreamSubscription._checkState (dart:async[/stream_impl.dart:449:9]())
#7      _BufferingStreamSubscription._sendData (dart:async[/stream_impl.dart:343:5]())
#8      _DelayedData.perform (dart:async[/stream_impl.dart:591:14]())
#9      _StreamImplEvents.handleNext (dart:async[/stream_impl.dart:706:11]())
#10     _PendingEvents.schedule.<anonymous closure> (dart:async[/stream_impl.dart:663:7]())
#11     _microtaskLoop (dart:async[/schedule_microtask.dart:40:21]())
#12     _startMicrotaskLoop (dart:async[/schedule_microtask.dart:49:5]())
#13     _runPendingImmediateCallback (dart:isolate-patch[/isolate_patch.dart:122:13]())
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch[/isolate_patch.dart:193:5]())
```
package:onepubdoc/src/documenter.dart:34

**Comment by simolus3** [comment]
This looks like a bug then, thanks for the report. Can you share the `.tar.gz` file with which it fails? There are some tests in this package decoding gzip tars, so it looks like it only happens for some files.

**Comment by bsutton** [comment]
The file that demos the bug is attached.

The tar is generated by the pub publish command and I suspect the bug exists in all of the tars generated by pub publish (as it occurs in any tar I try at random).
[2.0.1.tar.gz](https://github.com/simolus3/tar/files/8310101/2.0.1.tar.gz)

**Comment by simolus3** [comment]
I tried to plug that file into this script and it all worked for me:

```dart
import 'dart:io';

import 'package:tar/src/reader.dart';

Future<void> main() async {
  final source = File('2.0.1.tar.gz');

  await TarReader.forEach(
    source.openRead().transform(gzip.decoder),
    (entry) {
      print(entry.name);
    },
  );
}
```

I don't know what `core` is in your snippet, if this is from a repo that I can take a look at I'll try running that too. Even if it's caused by that code, this package should provide a much better error message so I'll consider this a bug in `package:tar`. I assume this is the source stream reacting weirdly to pause/resume events for some reason.

> The tar is generated by the pub publish command and I suspect the bug exists in all of the tars generated by pub publish (as it occurs in any tar I try at random).

That would surprise me as pub uses this package to read and write `.tar.gz` streams too :D

**Comment by simolus3** [comment]
FWIW your source with slight modifications works for me. I think there's something weird happening around `a.openWrite()`, on which Operating System are you running this?

```dart
Future<void> extractTar(
    String pathToTarGz, String pathToExtractionPoint) async {
  final reader =
      TarReader(File(pathToTarGz).openRead().transform(gzip.decoder));

  while (await reader.moveNext()) {
    final entry = reader.current;
    final path = join(pathToExtractionPoint, entry.name);
    switch (entry.type) {
      case TypeFlag.dir:
        final dir = Directory(path);
        if (!dir.existsSync()) {
          await dir.create(recursive: true);
        }
        break;

      case TypeFlag.reg:
      case TypeFlag.regA:
        // // write each entry from the tar to disk under the [tmp] folder
        final file = File(path);
        final parent = file.parent;
        if (!parent.existsSync()) {
          await parent.create(recursive: true);
        }
        final a = File(path);
        await entry.contents.pipe(a.openWrite());
        break;
      case TypeFlag.link:
      case TypeFlag.symlink:
        break;
      // ignore: no_default_cases
      default:
        throw Exception('$pathToTarGz $path Type: ${entry.type}');
    }
  }
  // }, create: false, suffix: 'tar.gz', keep: true);
}
```

**Comment by bsutton** [comment]
linux 64bit
S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
core is from the dcli package:

import 'package:dcli_core/dcli_core.dart' as core;


dart pub add dep dcli

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
running your version of the code still generated the same error.
S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by simolus3** [comment]
Thanks for the details. Somewhat unfortunately I'm also on x64 Linux and your snippet with dcli added still doesn't hit the assertion error for me. 

You could try using this version of `package:tar`? It should give slightly more details in the assertion error:

```yaml
dependency_overrides:
  tar:
    git:
      url: https://github.com/simolus3/tar.git
      ref: investigate-issue-21
```

----

This is slightly off-topic, but I also want to note that your extraction code would allow malicious tar files to override any file in your system. You can check the extraction logic [from pub](https://github.com/dart-lang/pub/blob/826e2086676ca27025b6b1237e930106f4c7937d/lib/src/io.dart#L903-L991) for some guards against this. If you're only using this for trusted tar files it's fine though.

**Comment by bsutton** [comment]
Here is a self contained app that demonstrates the problem.
[tarbug.zip](https://github.com/simolus3/tar/files/8310735/tarbug.zip)

**Comment by simolus3** [comment]
I can't reproduce this. The script from that zip extract the contents just fine for me when I pass the previously attached 2.0.1.tar.gz to it:

```
$ dart run bin/main.dart 2.0.1.tar.gz

Warning: 'dartdoc' is deprecated. Please use 'dart doc'.
Documenting background_app_bar...
Resolving dependencies...

dartdoc 4.1.0 (/home/simon/bin/dart-sdk/stable/bin/snapshots/dartdoc.dart.snapshot) failed: pub get failed: Resolving dependencies...

Because background_app_bar depends on flutter_test from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`..
```

This might be something specific to your (or, if we're unlucky, my) machine.

**Comment by bsutton** [comment]
What dart version are you running?

**Comment by simolus3** [comment]
I'm seeing the exact same behavior on the latest stable (2.16.1), beta (2.17.0-182.1.beta) and dev (2.17.0-212.0.dev).

**Comment by bsutton** [comment]
Maybe this will help:

```
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      BlockReader.nextBlocks.<anonymous closure> (package:tar/src/utils.dart:515:16)
#3      _runGuarded (dart:async/stream_controller.dart:814:24)
#4      _StreamController._recordPause (dart:async/stream_controller.dart:759:5)
#5      _ControllerSubscription._onPause (dart:async/stream_controller.dart:854:17)
#6      _BufferingStreamSubscription._checkState (dart:async/stream_impl.dart:449:9)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:343:5)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```
I"ve added some print statements and I can see moveNext is called 94 times and then fails.
This is repeatable.
The tar in question has 149 entries.

The last entry it processes is: example/macos/Runner.xcodeproj/project.pbxproj
It fails during the call to ```await entry.contents.pipe(a.openWrite());```
The call to pipe returns successfully but during the await the above stacktrace is generated.

**Comment by simolus3** [comment]
Can you print the value of `state` and `_remainingBlocksInOutgoing` when [this assertion](https://github.com/simolus3/tar/blob/7cdb563c9894600c6a739ec268f8673d6122006f/lib/src/utils.dart#L515) fails? I think that would be the most helpful values to get an idea of what's happening here, thanks!

It might be that the file is buffering (and this pausing the stream) just after all of the contents have been written. But that's a guess without seeing the actual state.

**Comment by bsutton** [comment]
I added a print statement to _emitBlocks: 296 which is just after it
updates the blocks remaining.
final remainingNow = _remainingBlocksInOutgoing -= amount;
print(_remainingBlocksInOutgoing);

It's interesting as for all of the other files it only ever prints 0.
For this file I see to prints:

52
51
0
So, I'm guessing this is the first large file.

I also wrapped the calls to _pause in _emitBlocks to output before and
after each pause event:
pausing2/paused2 is the second pause after the if (outgoing.isPaused ||
outgoing.isClosed)

52
pausing2
paused2
51
pausing2
paused2
0
paused1
paused1

I also wrapped the calls to outgoing.close() in _emitBlocks and it
doesn't gets called before the assert fires.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by simolus3** [comment]
I think I may have fixed the issue in 00deddcc38babc875a2226e1e307e1af69b1cc2a, could you please try the `investigate-issue-21` branch from this repo? If you still hit the failing assertion in that case, also having the exact message would be great.

**Comment by morlay** [comment]
@simolus3 works for me with `investigate-issue-21` 🥳 

```dart
final tgzFile = File(tgzFileName).openRead().transform(gzip.decoder);

await TarReader.forEach(tgzFile, (entry) async {
  final f = File(path.join(cache.absolute.path, entry.header.name));
  await f.create(recursive: true);
  await f.openWrite().addStream(entry.contents);
});
```

**Comment by simolus3** [comment]
Nice, I'll release this version then! By the way, if you use `addStream` you also need to close the file sink manually. `entry.contents.pipe(f.openWrite())` does this automatically.

**Comment by morlay** [comment]
Yes. got it.

Thank your cool works.

migrating from `archive`, 10+ times speed up

**Comment by simolus3** [comment]
I've just published version 0.5.5 which contains this fix. @bsutton, please let me know if you still run into this and I'll re-open this issue then.

> migrating from `archive`, 10+ times speed up

That's amazing to hear! I put a lot of effort into making things fast in this library, but I couldn't beat `package:archive` when reading from a stream because we have an async overhead, verify checksums and detect advanced tar headers. So just out of interest, what are you doing that makes this package appear so fast? :D

**Comment by morlay** [comment]
Just packing/unpacking lots of blobs by
tgz

For a 174MiB tgz file

With `package:archive`, 14s costs
With `package:tar`, 1.5s costs

**Comment by bsutton** [comment]
Just confirming that 0.5.5 resolved my issue.

Greatly appreciate the work !!!

**Comment by bsutton** [comment]
_AssertionError ('package:tar/src/utils.dart': Failed assertion: line 515
pos 16: 'state == _StreamState.initial || state == _StreamState.attached':
Unexpected pause event in _StreamState.done.)

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by simolus3** [comment]
That assertion doesn't match the code in the latest version of `package:tar`, could you try upgrading?
