### ISSUE TITLE
How append files?

### ISSUE THREAD

**Issue by krow89** [simolus3/tar#24]
Its possible append / edit files to tar with this library?

**Comment by simolus3** [comment]
Sure! You can edit or add tar entries by reading the source archive, transforming it, and then writing it again:

```dart
import 'dart:convert';
import 'dart:io';

import 'package:tar/tar.dart';

void main() async {
  final source = File('original.tar').openRead();
  final destination = tarWritingSink(File('modified.tar').openWrite());

  final reader = TarReader(source);
  while (await reader.moveNext()) {
    // Add the current entry to the output, you can also check its path to
    // conditionally modify or skip some files in the archive.
    // The current tar entry becomes invalid after calling moveNext() again, so
    // we need to use a method that allows us to await the operation
    await destination.addStream(Stream.value(reader.current));
  }

  // After adding the original archive, add more files.
  destination.add(TarEntry.data(
    TarHeader(name: 'foo.bar'),
    utf8.encode('hello world, new entry!'),
  ));

  // Complete writing the file
  await destination.close();
}

```

**Comment by krow89** [comment]
This mean that its needed a recreation of the archive, right? Its the only way? I have some archives with many files inside and edits can be made frequently.... Anyway, thank you

**Comment by simolus3** [comment]
I mean, we could probably be more efficient than re-writing the entire archive:

1. To append entries, we'd just have to remove the end-of-archive marker at the end of the tar file and then add new entries at the end of the file.
2. With a `RandomAccessFile`, we could potentially patch files to make other edits as well.

Maybe there could be an API for this, but the whole point of this package is to deal with tar files as non-seekable streams.

**Comment by krow89** [comment]
Understood... Again, thank you
