### ISSUE TITLE
[Question] How to read a tar from assets

### ISSUE THREAD

**Issue by CaptainDario** [simolus3/tar#31]
I have a tar.gz in my assets bundle, I would like to read that as a stream. Is that possible with this package?

**Comment by simolus3** [comment]
It is possible with this package. But you can't benefit from the steaming reader as much since there is no way to open an asset as a stream right now (https://github.com/flutter/flutter/issues/73322). Still, you can do something like:

```dart
final data = await bundle.load(...);
final reader = TarReader(Stream.value(data.asUint8List()).transform(gzip.decoder));

while (await reader.moveNext()) {
  // deal with tar entry
}
```

**Comment by CaptainDario** [comment]
Ah, that's a bummer. I considered using this package because of its streams.

I have a rather large archive (uncomoressed 400mb) that I want to unpack from assets. So that the UI is not blocked, I am unpacking it in a separate isolate. However, the root bundle is not accessible in an isolate. Therefore, the whole archive needs to be loaded into memory and then copied to the second isolate, which takes a lot of time _additional_ to the unpacking.

Maybe there is a workaround I am not aware of?

**Comment by simolus3** [comment]
To be fair you only need to load the compressed archive as a single blob, by invoking the gzip decoder as a stream transformer the decoding can still happen in smaller chunks.

> I was thinking about using a dart:ffi pointer and pass that to the isolate as the loaded data from root bundle is just a `Uint8List`?

Yeah that should work, but I think you need to copy to get a pointer from the `Uint8List`. So you might as well use a [`TransferrableTypedData`](https://api.dart.dev/stable/3.1.5/dart-isolate/TransferableTypedData-class.html) which can be moved across isolates - then you don't have to care about when to free memory.

**Comment by CaptainDario** [comment]
> Yeah that should work, but I think you need to copy to get a pointer from the `Uint8List`. So you might as well use a [`TransferrableTypedData`](https://api.dart.dev/stable/3.1.5/dart-isolate/TransferableTypedData-class.html) which can be moved across isolates - then you don't have to care about when to free memory.

Wow, thank you, this looks promising! However, the docs state

> A TransferableTypedData is created from a number of bytes. This will take time proportional to the number of bytes.

So, will this still copy the whole thing once? Or can I create this directly from the root bundle?

**Comment by CaptainDario** [comment]
> To be fair you only need to load the compressed archive as a single blob, by invoking the gzip decoder as a stream transformer the decoding can still happen in smaller chunks.

Would it be possible to just send the stream transformer to the isolate, thus avoiding the need of copying?

**Comment by simolus3** [comment]
> So, will this still copy the whole thing once? Or can I create this directly from the root bundle?

Yeah, it will copy. But if you want to convert the asset into an externally-managed buffer with `dart:ffi`, you'll have to copy once as well.

> Would it be possible to just send the stream transformer to the isolate, thus avoiding the need of copying?

The stream transformer alone is not that useful, and streams can't be sent over isolates since they need to track callbacks and the data source. I think copying the (compressed) asset once to move it to the background isolate (which would then do the decompression + tar reading) is likely the most efficient approach possible right now.

**Comment by CaptainDario** [comment]
@simolus3 thank you for your help! I will then stick with the frozen UI and unpacking it in the main isolate. Copying the data seems to take a **very** long time (the time to unpack the data nearly tripled)

I am not sure how you want to handle this issue, this would be a great feature to add in the future. Maybe you want to keep it open to track this feature.

**Comment by CaptainDario** [comment]
Well, I need to correct myself here, the slowdowns came from an update to the archive package. However, once streaming from assets and access to assets in an isolate is possible, would be great to use this in this package, then I would also switch to this package.

Here the related issues from the flutter repo

* https://github.com/flutter/flutter/issues/96895
* https://github.com/flutter/flutter/issues/73322

**Comment by simolus3** [comment]
I'll close this issue since nothing in this package is blocking it, Flutter just needs to expose streams for assets.

> Well, I need to correct myself here, the slowdowns came from an update to the archive package

Note that, while the total extraction time might be _slightly_ slower when using `package:tar`, there are many asynchronous suspension points allowing other parts of your app to run.
So it might be possible to extract gzipped tar files by loading the compressed blob into memory and then using a `TarReader(Stream.value(compressedData).transform(gzip.decoder))` without causing UI lags.
