### ISSUE TITLE
entry.contents.pipe hangs

### ISSUE THREAD

**Issue by bsutton** [simolus3/tar#32]
This is an odd one.

I've have existing code which has been working without issue for some time.

I've had to upgrade some of the packages for my app and now the untaring of files is hanging.

The problem is on the entry.contents.pipe(a.openWrite()) line.

``` dart

import 'package:dcli_core/dcli_core.dart' as core;

/// Extracts the contents of the the tar in [pathToTarGz] into
Future<void> extractTar(
    String pathToTarGz, String pathToExtractionPoint) async {
  final reader =
      TarReader(File(pathToTarGz).openRead().transform(gzip.decoder));

  while (await reader.moveNext()) {
    final entry = reader.current;
    final path = truepath(pathToExtractionPoint, entry.name);

    if (!path.startsWith(pathToExtractionPoint)) {
      // invalid path, may be hacking attempt.
      throw InvalidEntryInTar('$pathToTarGz $path Type: ${entry.type}');
    }
    print('untaring $path');
    switch (entry.type) {
      case TypeFlag.dir:
        if (!exists(path)) {
          core.createDir(path, recursive: true);
        }
        break;

      case TypeFlag.reg:
      case TypeFlag.regA:
        // write each entry from the tar to disk under the [tmp] folder
        if (!exists(dirname(path))) {
          core.createDir(dirname(path), recursive: true);
        }
        final a = File(path);
       /////////////////////////////////////// 
       /// hangs on the second call to the following line
      /////////////////////////////////////////////////////////////
          await entry.contents.pipe(a.openWrite());
        break;
      // ignore: no_default_cases
      default:
        throw UnexpectEntryTypeInTar('$pathToTarGz $path Type: ${entry.type}');
    }
  }
  // }, create: false, suffix: 'tar.gz', keep: true);
}

```

The `pipe` hangs on the first file in tries to untar.

I thought it might be a problem with the tar contents so I made the process skip the first file. It then stalled on the 'new' first file (the second file in the tar).

I've also tried this with multiple tar files and the same problem occurs.
I've tried changing my dart version from 3.2.5 back to 3.1.0 with no change.
I can't go to tar 1.0.4 due to other conflicts.

I've downloaded the tar source but I'm having trouble even finding where the stream gets read from.

Any suggestions as to where to start looking?

I've attached a sample tar that is exhibits the problem.

[dotfile.tar.gz](https://github.com/simolus3/tar/files/14340021/dotfile.tar.gz)

**Comment by bsutton** [comment]
So I found the problem.

The function calling extractTar was unawaited:

```dart
unawaited(extractTar(.... ));
```

So as soon as I changed the unawait to 'await' the problem went away.

I really don't understand what interaction between the pipe and being unawaited would cause the issue.

So I'm going to close the issue out but thought it worth creating this issue incase some else gets caught by this bizarre behaviour.

**Comment by simolus3** [comment]
That's pretty weird,  I think it should still work with the `unawaited`. The script crashes for me because `createDir` appears to be async and not awaited in `extractTarGz`,  so it fails with `OS Error: No such file or directory`.

I had to make some changes to get your script to compile, this is the file I've been using to reproduce this:

```dart
import 'dart:async';
import 'dart:io';

import 'package:dcli_core/dcli_core.dart' as core;
import 'package:path/path.dart';
import 'package:tar/tar.dart';

/// Extracts the contents of the the tar in [pathToTarGz] into
Future<void> extractTar(
    String pathToTarGz, String pathToExtractionPoint) async {
  final reader =
      TarReader(File(pathToTarGz).openRead().transform(gzip.decoder));

  while (await reader.moveNext()) {
    final entry = reader.current;
    final path = core.truepath(pathToExtractionPoint, entry.name);
    print('${entry.name}');

    if (!path.startsWith(pathToExtractionPoint)) {
      // invalid path, may be hacking attempt.
      throw '$pathToTarGz $path Type: ${entry.type}';
    }
    print('untaring $path');
    switch (entry.type) {
      case TypeFlag.dir:
        if (!core.exists(path)) {
          core.createDir(path, recursive: true);
        }
        break;

      case TypeFlag.reg:
      case TypeFlag.regA:
        // write each entry from the tar to disk under the [tmp] folder
        if (!core.exists(dirname(path))) {
          core.createDir(dirname(path), recursive: true);
        }
        final a = File(path);
        ///////////////////////////////////////
        /// hangs on the second call to the following line
        /////////////////////////////////////////////////////////////
        await entry.contents.pipe(a.openWrite());
        break;
      // ignore: no_default_cases
      default:
        throw '$pathToTarGz $path Type: ${entry.type}';
    }
  }
  // }, create: false, suffix: 'tar.gz', keep: true);
}

void main() async {
  unawaited(extractTar('/tmp/repro/test.tar.gz', '/tmp/repro/out'));
}
```

**Comment by bsutton** [comment]
I suspect it may be a broader interaction but it's part of a larger project
and hard to pull out the key pieces.

What I do know is that toggling between  unawaited and await reliably
reproduces/solves the issue.

You are right about the core.createDir being async. In my actual code
base I use the sync version and I did some manual modes when reporting this
issue to make it easier to reproduce and I then forgot to add the awaits.

If I have some time I will try to get back to this, but I'm a little
hammered at the moment.
